use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# RollbaxIssue81Web.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :rollbax_issue_81, RollbaxIssue81Web.Endpoint,
  load_from_system_env: false,
  url: [host: "${URL_HOSTNAME}", port: "${URL_PORT}"],
  cache_static_manifest: "priv/static/cache_manifest.json",
  http: [port: "${PORT}"],
  server: true,
  root: ".",
  version: Mix.Project.config[:version]

config :rollbax_issue_81, RollbaxIssue81Web.Endpoint,
  secret_key_base: "${SECRET_KEY_BASE}"

# TODO: This is an internal tool, so do this for now...
config :rollbax_issue_81, RollbaxIssue81Web.Endpoint,
  debug_errors: true

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :rollbax_issue_81, RollbaxIssue81Web.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [:inet6,
#               port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :rollbax_issue_81, RollbaxIssue81Web.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :rollbax_issue_81, RollbaxIssue81Web.Endpoint, server: true
#

# Configure your database
config :rollbax_issue_81, RollbaxIssue81.Repo,
  adapter: Ecto.Adapters.Postgres,
  hostname: "${PG_HOST}",
  port:     "${PG_PORT}",
  username: "${PG_USER}",
  password: "${PG_PASS}",
  database: "${PG_DATABASE}",
  pool_size: 15

# Rollbar: https://hexdocs.pm/rollbax
config :rollbax,
   access_token: "735fce638507497c8d43327f030381a6",
   environment: "${ENVIRONMENT}"

# Finally import the config/prod.secret.exs
# which should be versioned separately.
import_config "prod.secret.exs"
